apply plugin: "com.android.library"
apply plugin: "org.jetbrains.kotlin.android"

group = "cl.studia.voz"
version = "0.1.0"

android {
  namespace "cl.studia.voz"
  compileSdk rootProject.ext.compileSdkVersion

  defaultConfig {
    minSdk rootProject.ext.minSdkVersion
    targetSdk rootProject.ext.targetSdkVersion
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }
  kotlinOptions { jvmTarget = "17" }
}

dependencies {
  implementation project(":expo-modules-core")
  implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"
}
